# Generated by Django 2.2.7 on 2020-02-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depensesbudget',
            name='titre',
            field=models.CharField(max_length=101),
        ),
    ]
