# Generated by Django 2.2.7 on 2020-02-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0003_category_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='restant',
            field=models.IntegerField(),
        ),
    ]
